
CREATE TABLE `sku_data` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `REPORTED_SKU_CODE` varchar(255) DEFAULT NULL,
  `TARGET_SKU_CODE` varchar(255) DEFAULT NULL,
  `QUANTITY` int DEFAULT NULL,
  `PARTNER_NAME` varchar(255) DEFAULT NULL,
  `PARTNER_CODE` varchar(255) DEFAULT NULL,
  `COUNTRY` varchar(255) DEFAULT NULL,
  `REGION` varchar(255) DEFAULT NULL,
  `ACTION` varchar(255) DEFAULT NULL,
  `USER_COMMENTS` varchar(255) DEFAULT NULL,
  `STRATEGY` varchar(255) DEFAULT NULL,
  `IS_BASE_SKU` tinyint(1) DEFAULT NULL,
  `start_date` varchar(255) DEFAULT NULL,
  `end_date` varchar(255) DEFAULT NULL,
  `BOM_USAGE_FLAG` tinyint(1) DEFAULT NULL,
  `SEQUENCE_NUMBER` int DEFAULT NULL,
  PRIMARY KEY (`ID`)
);
