CREATE TABLE MASTER_METADATA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MASTER_NAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

drop table if exists MASTER_FIELD_METADATA;

CREATE TABLE MASTER_FIELD_METADATA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MASTER_ID INT NOT NULL,
    FIELD_NAME VARCHAR(255) NOT NULL,
    FIELD_COLUMN_NAME VARCHAR(255) NOT NULL,  -- New column for the actual column name in the master data table
    DATA_TYPE VARCHAR(50) NOT NULL,
    MAX_LENGTH INT,
    IS_NOT_NULL BOOLEAN DEFAULT FALSE,
    IS_UNIQUE BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (MASTER_ID) REFERENCES MASTER_METADATA(ID) ON DELETE CASCADE
);

INSERT INTO MASTER_METADATA (MASTER_NAME) VALUES ('PARTNER_MASTER');


INSERT INTO MASTER_FIELD_METADATA (MASTER_ID, FIELD_NAME, FIELD_COLUMN_NAME, DATA_TYPE, MAX_LENGTH, IS_NOT_NULL, IS_UNIQUE) 
VALUES 
(1, 'id', 'ID', 'INT', NULL, TRUE, FALSE),               -- Primary Key
(1, 'PartnerCode', 'PARTNER_CODE', 'VARCHAR', 50, TRUE, TRUE),    -- Unique field
(1, 'PartnerName', 'PARTNER_NAME', 'VARCHAR', 100, TRUE, FALSE),   -- Not Null
(1, 'PartnerType', 'PARTNER_TYPE', 'VARCHAR', 50, FALSE, FALSE),   -- Optional
(1, 'Region', 'REGION', 'VARCHAR', 50, FALSE, FALSE),        -- Optional
(1, 'subRegion', 'SUB_REGION', 'VARCHAR', 50, FALSE, FALSE),     -- Optional
(1, 'Country', 'COUNTRY', 'VARCHAR', 50, FALSE, FALSE);       -- Optional
